### ISSUE TITLE
UnboundLocalError from unauthorised cascading query

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/dqsegdb#12]
If I try an unauthorised, cascading query from the command line, I get to an `UnboundLocalError`:

``` bash
$ ligolw_segment_query_dqsegdb -q -t https://segments.ligo.org -s 1116806416 -e 1116892816 -a L1:ODC-INJECTION_DETCHAR
Could not find a valid proxy credential.
LIGO users, please run 'ligo-proxy-init' and try again.
Others, please run 'grid-proxy-init' and try again.

Warning:  No proxy found or other error encountered during check for authentication credentials, connections to https will not work.
Warning: Issue accessing url: https://segments.ligo.org/dq/L1/ODC-INJECTION_DETCHAR
Code: 
401
Message: 
Unauthorized
May be handled cleanly by calling instance: otherwise will result in an error.
Traceback (most recent call last):
  File "/opt/local/bin/ligolw_segment_query_dqsegdb", line 751, in <module>
    run_query_segments_dqsegdb(doc, process_id, protocol, server, gps_start_time, gps_end_time, options.include_segments, options.exclude_segments, options.result_name)
  File "/opt/local/bin/ligolw_segment_query_dqsegdb", line 525, in run_query_segments_dqsegdb
    json_result,versioned_JSON,affected_results=apicalls.dqsegdbCascadedQuery(protocol, server, ifo, name, include_list_string, startTime, endTime)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dqsegdb/apicalls.py", line 573, in dqsegdbCascadedQuery
    result_flag,affected_results=clientutils.calculate_versionless_result(jsonResults,startTime,endTime,ifo_input=ifo)
UnboundLocalError: local variable 'jsonResults' referenced before assignment
```

Surely this should end up with a 401 error?

This is using v1.2.2 of the dqsegdb port on OSX.

**Comment by rpfisher** [comment]
Yes, this is an improperly handled exception, will be fixed.

**Comment by robertbruntz** [comment]
Comments on issue #40 ( https://github.com/ligovirgo/dqsegdb/issues/40 ) indicate that the underlying issue has been resolved.  Testing the original query on detchar-cit without authorization (i.e., X509_USER_CERT and X509_USER_KEY not pointing to a valid cert) now produces a new, appropriate error ("RuntimeError: Could not find a RFC 3820 compliant proxy credential. Please run 'grid-proxy-init -rfc' and try again."), so the issue seems to be resolved.
