### ISSUE TITLE
ligolw_combine_segments broken with latest lscsoft-glue

### ISSUE THREAD

**Issue by ahnitz** [ligovirgo/dqsegdb#46]
```
(env)ahnitz@atlas4:~/projects/O2fit/t1/21/gw/output/local-site-scratch/work/gw-main_ID0000001$ /home/ahnitz/projects/O2fit/t1/env/bin/ligolw_combine_segments L1-VETOTIME_CAT1-1186624818-687900.xml L1-VETOTIME_CAT3-1186624818-687900.xml L1-VETOTIME_CAT2-1186624818-687900.xml --segment-name CUMULATIVE_CAT_12H --output L1-LIGOLW_COMBINE_SEGMENTS_CUMULATIVE_CAT_12H-1186624818-687900.xml
Traceback (most recent call last):
  File "/home/ahnitz/projects/O2fit/t1/env/bin/ligolw_combine_segments", line 146, in <module>
    row = copy.copy(base_row)
  File "/usr/lib/python2.7/copy.py", line 96, in copy
    return _reconstruct(x, rv, 0)
  File "/usr/lib/python2.7/copy.py", line 336, in _reconstruct
    y.__setstate__(state)
  File "/home/ahnitz/projects/O2fit/t1/env/local/lib/python2.7/site-packages/glue/ligolw/table.py", line 560, in __setstate__
    self.__init__(**state)
TypeError: __init__() got an unexpected keyword argument 'segment_def_cdb'
```

Unless someone can fix this, can I request that dqsegdb require lscsoft-glue <= v1.56.0 and no later.

**Comment by duncanmmacleod** [comment]
@ahnitz, can you post a minimal command-line that produces the issue that we can use to test a fix? I can't seem to locate the files you are referring to in your original post.

**Comment by duncanmmacleod** [comment]
wait, why is this a DQSEGDB issue? `ligolw_combine_segments` is from `lscsoft-glue`, so please report the issue on https://git.ligo.org/lscsoft/glue.

**Comment by ahnitz** [comment]
good point
