### ISSUE TITLE
insert option in ligolw_segment_insert_dqsegdb cannot handle files over ~24k lines

### ISSUE THREAD

**Issue by robertbruntz** [ligovirgo/dqsegdb#86]
Description:
Executing a command like `ligolw_segment_insert_dqsegdb  -t https://segments.ligo.org  --insert  -i G1  --name=TEST_FLAG_007  --version=1  -e 'test explanation' -c 'test comment'  -S known.txt  -G active.txt` with `known.txt` and/or `active.txt` being over some value that seems to lie between 24k and 25k lines produces an error similar to the following (adapted from a real case, not exactly matching the above details):

> /usr/lib/python2.7/site-packages/dqsegdb/urifunctions.py:303: UserWarning: Info: Flag does not exist in database yet for url: https://segments.ligo.org/dq/H1/DCH-POP_LOUD_GLITCHES/3
>   warn("Info: Flag does not exist in database yet for url: %s" % url)
> /usr/lib/python2.7/site-packages/dqsegdb/urifunctions.py:295: UserWarning: Warning: Issue accessing url: https://segments.ligo.org/dq/H1/DCH-POP_LOUD_GLITCHES/3
>   warn("Warning: Issue accessing url: %s" % url)
> /usr/lib/python2.7/site-packages/dqsegdb/urifunctions.py:296: UserWarning: Code: 500
>   warn("Code: %s" % str(e.code))
> /usr/lib/python2.7/site-packages/dqsegdb/urifunctions.py:297: UserWarning: Message: Internal Server Error
>   warn("Message: %s" % str(e.msg))
> /usr/lib/python2.7/site-packages/dqsegdb/urifunctions.py:300: UserWarning: May be handled cleanly by calling instance: otherwise will result in an error.
>   warn("May be handled cleanly by calling instance: otherwise will result in an error.")
> Traceback (most recent call last):
>   File "/usr/bin/ligolw_segment_insert_dqsegdb", line 446, in <module>
>     publishAndExit(filepath,debug)
>   File "/usr/bin/ligolw_segment_insert_dqsegdb", line 184, in publishAndExit
>     result=callInsertMultipleDQXMLThreaded(filepath,debug)
>   File "/usr/bin/ligolw_segment_insert_dqsegdb", line 204, in callInsertMultipleDQXMLThreaded
>     result=apicalls.InsertMultipleDQXMLFileThreaded(infiles,logger,options.segment_url,hackDec11=False,debug=debug,threads=1)
>   File "/usr/lib/python2.7/site-packages/dqsegdb/apicalls.py", line 1083, in InsertMultipleDQXMLFileThreaded
>     patchWithFailCases(i,url,debug,logger,testing_options)
>   File "/usr/lib/python2.7/site-packages/dqsegdb/apicalls.py", line 694, in patchWithFailCases
>     raise ee
> urllib2.HTTPError: HTTP Error 500: Internal Server Error
> 

Workaround:
If a file is split, `active` segments must be within the time period of the `known` segments (e.g., in a trivial example, if `known` segments span [A,D) and `active` segments span [A,B) and [C,D), the `active` segments cannot be split into one file for [A,B) and another for [C,D) while keeping the `known` segments in one file for [A,D); the `known` segments would also have to be split into two files, one starting at A and ending anywhere between B and C and a second starting at the time that the first ended at and ending at D).

Instructions for how to deal with a file with 2 known segments and a file with 38k active segments (from 2021.03.09, in DetChar Computing Slack channel):
- The `known.txt` files for each run will need to be split to cover the same total time period but each will have to cover the segments in the corresponding active file.  This is important, since misaligning these can cause difficult-to-fix issues, but setting it up the right way shouldn’t be difficult, if I’ve explained it properly.
- If the 2 `known` segments each cover < 24k `active` segments, then it’s easy - just split into `known1` and `known2` and corresponding `active1` and `active2`.
- If not, then you can split the active segments anywhere, into `active1` and `active2`, so long as each file is < 24k lines.  Then, split `known` into `known1` and `known2`, where 1 of the 2 `known` segments will be split from [A,C) to [A,B) in one file and [B,C) in the other file, where the `active` segments in `active1` end at or before time B and the `active` segments in `active2` start at or after B.

Derek Davis used this to split a large file (and manually split the `known` file into 2 parts that covered the corresponding `active` files without any gaps):
> split -a 1 -d -l 20000 active.txt active_chunk_   # splits active.txt, with ~38k lines, into active_chunk_0 (20k lines) and active_chunk_1 (~18k lines)

Ryan Fisher said that he thinks that the issue is in the client code, not MariaDB itself or the server-side code.

Some investigation into this has not yet yielded a cause for the limitation.

It is not known if this bug persists in the Python 3 version of the code.

When this bug is resolved, update the `--help` entries for `dqsegdb/bin/ligolw_segment_insert_dqsegdb`, which currently reference this issue #.

**Comment by robertbruntz** [comment]
This issue is being closed because it has been moved to the new repo, here: https://git.ligo.org/computing/dqsegdb/client/-/issues/86
