### ISSUE TITLE
ligolw_segment_insert_dqsegdb fails under Python 3 with a pyRXPU error about UTF-16 and UTF-8

### ISSUE THREAD

**Issue by robertbruntz** [ligovirgo/dqsegdb#90]
Issue:

When ligolw_segment_insert_dqsegdb is run on Python 3, it fails with a message that seems to come from `glue/ldbd.py`, which is using pyRXPU as an xml parser:
`pyRXPU.error: Declared encoding UTF-8 is incompatible with UTF-16 which was used to read it
Internal error, ParserPush failed!`

To reproduce:

On a CIT machine, activate a Python 3 IGWN Conda environment (e.g., `conda activate igwn-py38`), then run a command like this: `ligolw_segment_insert_dqsegdb  --insert  --segment-url=http://segments-backup.ldas.cit  --ifos=G1  --name=TEST_FLAG_GPS_TIME_1323707458  --version=1  -S /home/detchar/dqsegdb/known_segments_test_file.txt  -G /home/detchar/dqsegdb/active_segments_test_file.txt  --explain="This is a test flag published by test_segments_machine.sh on detchar-cit in a run started at GPS time 1323707458."    --comment="This is a test flag published by test_segments_machine.sh on detchar-cit in a run started at GPS time 1323707458."`

Command should fail and output should be something like this:
```
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38/bin/ligolw_segment_insert_dqsegdb", line 446, in <module>
    publishAndExit(filepath,debug)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38/bin/ligolw_segment_insert_dqsegdb", line 184, in publishAndExit
    result=callInsertMultipleDQXMLThreaded(filepath,debug)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38/bin/ligolw_segment_insert_dqsegdb", line 204, in callInsertMultipleDQXMLThreaded
    result=apicalls.InsertMultipleDQXMLFileThreaded(infiles,logger,options.segment_url,hackDec11=False,debug=debug,threads=1)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38-20211019/lib/python3.8/site-packages/dqsegdb/apicalls.py", line 795, in InsertMultipleDQXMLFileThreaded
    segment_md = setupSegment_md(filename,xmlparser,lwtparser,debug)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38-20211019/lib/python3.8/site-packages/dqsegdb/apicalls.py", line 734, in setupSegment_md
    segment_md.parse(xmltext)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py38-20211019/lib/python3.8/site-packages/glue/ldbd.py", line 382, in parse
    ligolwtup = self.xmlparser(xml)
pyRXPU.error: Declared encoding UTF-8 is incompatible with UTF-16 which was used to read it
Internal error, ParserPush failed!
```

**Comment by duncanmmacleod** [comment]
This is fixed by https://git.ligo.org/lscsoft/glue/-/merge_requests/84.

**Comment by robertbruntz** [comment]
The `glue` MR was merged, resolving the issue.
